apiVersion: skaffold/v1
kind: Config
metadata:
  name: migrate-de-db
deploy:
  kubectl:
    manifests:
      - k8s/migrate-de-db.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/de-database
  local: {}